Question 0:

In [8]:
# string methods

#count()
txt ="hi hi hi "
x = txt.count("hi")
print(x)

#split()

txt = "i love FMML"
x = txt.split(" ")
print(x)

#replace()
x = txt.replace("FFML", "IIITH")
print(x)

3
['i', 'love', 'FMML']
i love FMML


In [15]:
#List methods

#append()
Algo = ['AL', 'ML']
Algo.append("DL")
print(Algo)

#insert()
Algo.insert(1, "DP")
print(Algo)

#reverse()
Algo.reverse()
print(Algo)




['AL', 'ML', 'DL']
['AL', 'DP', 'ML', 'DL']
['DL', 'ML', 'DP', 'AL']


In [19]:
#Tuples

#count()
t = (1, 3, 7, 8, 7, 5, 4, 6, 8, 5)

x = t.count(7)

print(x)

#index()
x = t.index(8)

print(x)

2
3


In [22]:
#sets

#add()

num = {"one", "two", "three"}
num.add("four")
print(num)

#copy()

x = num.copy()
print(x)

#difference()

z = x.difference(num)
print(z)

{'one', 'four', 'two', 'three'}
{'one', 'four', 'two', 'three'}
set()


In [29]:
#dictionaries

#get()

nums = {
  1: "one",
  2: "two",
  3: "three"
}
x = nums.get(2)
print(x)

#values()

x = nums.values()
print(x)

#items()

x = nums.items()
print(x)

two
dict_values(['one', 'two', 'three'])
dict_items([(1, 'one'), (2, 'two'), (3, 'three')])


Question 1:

In [33]:
def revadd(str1,str2):
  res=str1[::-1]
  res=res+str2
  return res

a=revadd("abc","def")
print(a)

cbadef


Question 2:

In [37]:
work_hours = [('Abby',100 , 'F'),('Billy',400, 'M'),('Cassie',800,'F'), ('Maggi',600,'F'),('Alex',500,'M'),('Raj',225,'M'),('Penny',920,'F'),('Ben',300,'M')]
max=0
name=""
for x in work_hours:
  for y in x:
    if(y=='F' and max<=x[1]):
      max=x[1]
      name=x[0]
print(name)
print(max*20)

Penny
18400


Question 3 :
(a)

In [54]:
import numpy as np

a=np.arange(1,6)
x=np.vstack((a,a,a,a,a))
res=x.T
res

array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5]])

Question 3: (b)

In [55]:
b=np.arange(0,25).reshape(5,5)
print(b)
res@b

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 50,  55,  60,  65,  70],
       [100, 110, 120, 130, 140],
       [150, 165, 180, 195, 210],
       [200, 220, 240, 260, 280],
       [250, 275, 300, 325, 350]])